# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form/MainWindow.ui',
# licensing of 'form/MainWindow.ui' applies.
#
# Created: Mon Apr 20 21:14:30 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1405, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_home = QtWidgets.QWidget()
        self.tab_home.setObjectName("tab_home")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_home)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab_home)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.tab_home)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.tab_home)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.budget_table = QtWidgets.QTableView(self.tab_home)
        self.budget_table.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.budget_table.setObjectName("budget_table")
        self.verticalLayout.addWidget(self.budget_table)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_home)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_home)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.io_new = QtWidgets.QPushButton(self.tab_home)
        self.io_new.setObjectName("io_new")
        self.horizontalLayout.addWidget(self.io_new)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.asset_table = QtWidgets.QTableView(self.tab_home)
        self.asset_table.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.asset_table.setObjectName("asset_table")
        self.verticalLayout_2.addWidget(self.asset_table)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_home, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dateFrom = QtWidgets.QDateEdit(self.tab_2)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.horizontalLayout_5.addWidget(self.dateFrom)
        self.budget = QtWidgets.QComboBox(self.tab_2)
        self.budget.setEditable(True)
        self.budget.setObjectName("budget")
        self.horizontalLayout_5.addWidget(self.budget)
        self.asset = QtWidgets.QComboBox(self.tab_2)
        self.asset.setEditable(True)
        self.asset.setObjectName("asset")
        self.horizontalLayout_5.addWidget(self.asset)
        self.search = QtWidgets.QLineEdit(self.tab_2)
        self.search.setObjectName("search")
        self.horizontalLayout_5.addWidget(self.search)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.trans_table = QtWidgets.QTableView(self.tab_2)
        self.trans_table.setObjectName("trans_table")
        self.verticalLayout_3.addWidget(self.trans_table)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1405, 29))
        self.menubar.setObjectName("menubar")
        self.menuSavings = QtWidgets.QMenu(self.menubar)
        self.menuSavings.setObjectName("menuSavings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSavings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Savings", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Budgets", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Assets", None, -1))
        self.io_new.setText(QtWidgets.QApplication.translate("MainWindow", "Income/Outcome", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_home), QtWidgets.QApplication.translate("MainWindow", "Home", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Transactions", None, -1))
        self.menuSavings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Savings", None, -1))

